### ISSUE TITLE
Spark 4 crash

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-firmware#341]

**Comment by steersbob** [comment]
[coredump-astephon.txt](https://github.com/BrewBlox/brewblox-firmware/files/7634481/coredump-astephon.txt)
[coredump-astephon-b64.txt](https://github.com/BrewBlox/brewblox-firmware/files/7634485/coredump-astephon-b64.txt)
Core dump interpreted with firmware release 2021-11-29 3b77d006

**Comment by elcojacobs** [comment]
This might be related:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/lwip.html#limitations
