### ISSUE TITLE
Valve control

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-firmware#41]

**Comment by tgangso** [comment]
Upvoted :)

**Comment by tgangso** [comment]
Any status updates on this?
Thanks

**Comment by x24esru** [comment]
Will this include allowing an option for a DS2408 to operate as an 8 channel actuator analogous to the 2 channel DS2413?

**Comment by elcojacobs** [comment]
Yes, I think I will code it like that.
