### ISSUE TITLE
PWM still requesting power on balancer even if not in use

### ISSUE THREAD

**Issue by glibersat** [BrewBlox/brewblox-firmware#58]
When using a PWM and stopping it from an attached PID, the PWM will sometimes still requiring power from the power balancer, thus preventing other PWMs to use 100% of the power available.
Worse, it could leave some heating element or pump on even after disabling a setpoint, which could lead to heating element damage.

**Comment by elcojacobs** [comment]
Thanks, noted.
This is how it is supposed to work: when going from enabled to disabled, the PID should set the actuator to zero.
It should stop manipulating the actuator afterwards, so the actuator can be set manually.
